import type { Pose } from './types'

export const POSES: Pose[] = [
  // SEAT
  {
    id: 'skosnor', slug: 'skosnor', name_no: 'Skosnor', name_en: 'Shoelace',
    category: 'SEAT', archetype: 'Shoelace',
    function_desc: 'Stretch – gluteus, dype hofterotatorer',
    muscle_groups: ['Gluteus', 'Hofterotatorer'],
    meridian_tension: ['Galleblære'], meridian_compress: ['Lever'],
    intensity_label: 'Høy', intensity_level: 5,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: 'Ekstern rotasjon + adduksjon hoften. Tensjon i gluteus, kompresjon lysken.',
    is_active: true, sort_order: 1,
    instruksjon: [
      'Sitt med korslagte ben og legg ett kne direkte over det andre – knærne skal ligge nesten oppå hverandre.',
      'Plasser hendene foran deg og bøy deg rolig fremover. La ryggen runde naturlig fra korsryggen og oppover.',
      'Hodet henger tungt. Slipp nakken fullstendig.',
      'Hold vekten jevnt i sittebenene – ikke len deg fremover i knærne.',
    ],
    tilpasning: 'Sitt på en brettet teppe eller pute for å løfte hoften om korsryggen er stiv. Prøv en sidestrekk eller vri i stedet for å bøye rett frem.',
    kontraindikasjon: 'Unngå ved akutte kneskader. Dersom det kjennes i knærne og ikke hoften – sitt høyere eller bytt til halv skosnor.',
  },
  {
    id: 'halv_skosnor', slug: 'halv_skosnor', name_no: 'Halv skosnor', name_en: 'Half Shoelace',
    category: 'SEAT', archetype: 'Shoelace',
    function_desc: 'Stretch – gluteus (ensidig)',
    muscle_groups: ['Gluteus'],
    meridian_tension: ['Galleblære'], meridian_compress: ['Lever'],
    intensity_label: 'Medium', intensity_level: 3,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: 'Mildere versjon, godt startpunkt',
    is_active: true, sort_order: 2,
    instruksjon: [
      'Sitt med ett ben rett frem og det andre brettet inn på utsiden av det strake benet.',
      'Bøy deg rolig fremover langs det strake benet. La ryggen runde og hodet henge.',
      'Grip om ankelen eller foten – bruk grepet som et ankerfeste for å fordype strekket.',
      'Husk å bytte side.',
    ],
    tilpasning: 'Bøy gjerne kneet på det strake benet litt i starten. Bruk en remme rundt foten dersom du ikke når frem.',
    kontraindikasjon: 'Unngå om du har isjias – løft hoften med en pute slik at knærne er under hoftnivå.',
  },
  {
    id: 'sovende_svane', slug: 'sovende_svane', name_no: 'Sovende svane', name_en: 'Sleeping Swan',
    category: 'SEAT', archetype: 'Shoelace',
    function_desc: 'Stretch – gluteus, piriformis',
    muscle_groups: ['Gluteus', 'Piriformis'],
    meridian_tension: ['Galleblære'], meridian_compress: ['Lever'],
    intensity_label: 'Høy', intensity_level: 5,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: 'Yin-versjon av due-pose',
    is_active: true, sort_order: 3,
    instruksjon: [
      'Fra knestående, skyv ett kne frem mellom hendene og ut mot siden. Det fremre kneet peker ut, foten peker mot den andre hoften.',
      'La det bakre benet gli rett bakover og senk hoften mot gulvet.',
      'Bøy overkroppen fremover og hvil pannen på gulvet, en bolster eller underarmene.',
      'Pust rolig og la tyngden synke ned i hoften for hvert utpust.',
    ],
    tilpasning: 'Legg en foldet teppe under det fremre setet om hoften henger i luften. Jo mer foten er trukket inn mot hoften, jo mildere – skyv den frem for mer intensitet.',
    kontraindikasjon: 'Unngå ved akutte problemer i SI-leddet. Smerter i kneet – trekk foten nærmere hoften.',
  },
  {
    id: 'sal', slug: 'sal', name_no: 'Sal', name_en: 'Saddle',
    category: 'SEAT', archetype: 'Saddle',
    function_desc: 'Stretch – quad, hoftebøyere, ryggekstensjon',
    muscle_groups: ['Quadriceps', 'Hoftebøyere'],
    meridian_tension: ['Milt/mage'], meridian_compress: ['Blære/nyre'],
    intensity_label: 'Høy', intensity_level: 5,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: 'Intern rotasjon hoften mulig, ryggliggende versjon = supta virasana',
    is_active: true, sort_order: 4,
    instruksjon: [
      'Sett deg mellom eller på hælene med knærne samlet eller litt fra hverandre.',
      'Plasser hendene bak deg på gulvet og len deg forsiktig bakover. Stopp der du kjenner strekket.',
      'Gå videre til albuene om det er mulig, og til slutt legg ryggen flat på gulvet.',
      'La korsryggen bue og magen løfte seg. Pust dypt ned i magen.',
      'For å komme ut: rull til én side og rett ut bena ett om gangen.',
    ],
    tilpasning: 'Legg en bolster eller brettet teppe under ryggen for støtte. Spre knærne litt for å redusere trykket.',
    kontraindikasjon: 'Ta hensyn til kne- og ankelsmerter – ikke forsér. Unngå om du har akutt korsryggproblematikk.',
  },
  {
    id: 'halv_sal', slug: 'halv_sal', name_no: 'Halv sal', name_en: 'Half Saddle',
    category: 'SEAT', archetype: 'Saddle',
    function_desc: 'Stretch – quad/hoftebøyer (ensidig)',
    muscle_groups: ['Quadriceps', 'Hoftebøyere'],
    meridian_tension: ['Milt/mage'], meridian_compress: ['Blære/nyre'],
    intensity_label: 'Medium', intensity_level: 3,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: 'God introduksjon til full sal',
    is_active: true, sort_order: 5,
    instruksjon: [
      'Sitt med ett ben bøyd inn slik at foten er ved siden av hoften, det andre benet strekkes rett frem.',
      'Plasser hendene bak deg og len deg rolig bakover over det bøyde benet.',
      'Stopp der du kjenner strekket i låret eller hoftebøyeren. Kom ut ved å rulle til siden.',
    ],
    tilpasning: 'God introduksjon til full sal. Legg en pute under det bøyde kneet om det er ubehagelig.',
    kontraindikasjon: 'Ubehag i kneet – sjekk at foten er ved siden av hoften, ikke under. Ikke forsér.',
  },
  {
    id: 'drage', slug: 'drage', name_no: 'Drage', name_en: 'Dragon',
    category: 'SEAT', archetype: 'Saddle',
    function_desc: 'Stretch – hoftebøyer (psoas, iliacus)',
    muscle_groups: ['Hoftebøyere', 'Psoas'],
    meridian_tension: ['Milt/mage'], meridian_compress: ['Blære/nyre'],
    intensity_label: 'Medium-Høy', intensity_level: 4,
    duration_min_sec: 120, duration_max_sec: 300,
    notes: 'Utfall-posisjon, fremre kne over ankel',
    is_active: true, sort_order: 6,
    instruksjon: [
      'Fra knestående eller nedoverhund, ta ett langt skritt frem mellom hendene.',
      'Kne rett over hæl på det fremre benet. Skyv det bakre kneet bakover til du kjenner strekket foran i hoften.',
      'Hold hendene på gulvet på begge sider av foten, eller legg dem på det fremre låret for å løfte overkroppen.',
      'Sink hoften rolig ned for hvert utpust. Bytt side.',
    ],
    tilpasning: 'Legg en teppe under det bakre kneet. Dragon Flying High: løft hendene til låret og åpne brystet. Dragon Flying Low: gå ned på albuene innenfor foten.',
    kontraindikasjon: 'Ubehag i knekoppen – legg teppe under eller løft bakbenet ved å tukke tærne under.',
  },
  {
    id: 'sommerfugl', slug: 'sommerfugl', name_no: 'Sommerfugl', name_en: 'Butterfly',
    category: 'SEAT', archetype: 'Caterpillar',
    function_desc: 'Stretch – hamstrings, adductorer, ryggen',
    muscle_groups: ['Hamstrings', 'Adductorer'],
    meridian_tension: ['Nyre/blære'], meridian_compress: ['Milt/mage'],
    intensity_label: 'Medium', intensity_level: 3,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: 'Mild fleksjon ryggrad + ekstern rot. hoften',
    is_active: true, sort_order: 7,
    instruksjon: [
      'Sitt med fotsålene mot hverandre. Skyv føttene litt fremover fra deg – ikke trekk dem inn mot lysken.',
      'La ryggen runde seg naturlig og bøy rolig fremover. Hodet henger tungt ned mot hælene.',
      'Legg hendene lett på føttene eller på gulvet foran deg. Slipp alt muskulært hold.',
    ],
    tilpasning: 'Sett deg på en pute om korsryggen er stiv. Jo nærmere føttene er mot lysken, jo mer indre lår. Jo lenger frem – jo mer hamstrings og rygg.',
    kontraindikasjon: 'Unngå om du har isjias. Behold rett rygg om du har korsryggplager der fleksjon ikke er anbefalt.',
  },
  {
    id: 'halv_sommerfugl', slug: 'halv_sommerfugl', name_no: 'Halv sommerfugl', name_en: 'Half Butterfly',
    category: 'SEAT', archetype: 'Caterpillar',
    function_desc: 'Stretch – hamstrings (ensidig)',
    muscle_groups: ['Hamstrings'],
    meridian_tension: ['Nyre/blære'], meridian_compress: ['Milt/mage'],
    intensity_label: 'Medium', intensity_level: 3,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: 'Ligner Janu Sirsasana, godt for stive hamstrings',
    is_active: true, sort_order: 8,
    instruksjon: [
      'Sitt med ett ben rett frem. Brett det andre inn mot lysken.',
      'La haken falle mot brystet, bøy deg fremover langs det strake benet.',
      'Grip foten eller ankelen – bruk grepet som et ankerfeste. La ryggen runde fra korsryggen.',
    ],
    tilpasning: 'Bøy kneet på det strake benet litt om hamstrings er stive. Bruk en remme rundt foten.',
    kontraindikasjon: 'Unngå om du har isjias – løft setet med en pute.',
  },
  {
    id: 'oyenstikker', slug: 'oyenstikker', name_no: 'Øyenstikker', name_en: 'Dragonfly',
    category: 'SEAT', archetype: 'Dragonfly',
    function_desc: 'Stretch – adductorer, groin',
    muscle_groups: ['Adductorer'],
    meridian_tension: ['Lever'], meridian_compress: ['Milt/mage', 'Galleblære'],
    intensity_label: 'Høy', intensity_level: 5,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: 'Bred bein-separasjon, kompresjon lyske',
    is_active: true, sort_order: 9,
    instruksjon: [
      'Sitt med bena bredt utstrakt til sidene – så langt de vil uten at du anstrenger deg.',
      'Lean rolig fremover og støtt deg på hendene eller albuene. La ryggen runde naturlig.',
      'Bøy gjerne over ett bein om gangen for variasjon. Strekket er dypt – gi deg god tid.',
    ],
    tilpasning: 'Sitt på en pute for å vinkle hoften fremover. Øyenstikker kan ta lang tid å åpne – ikke forvent rask fremgang.',
    kontraindikasjon: 'Unngå om du har isjias. Ubehag innerst i kneet – trekk bena litt nærmere hverandre.',
  },
  {
    id: 'frosk', slug: 'frosk', name_no: 'Frosk', name_en: 'Frog',
    category: 'SEAT', archetype: 'Dragonfly',
    function_desc: 'Stretch – adductorer, groin (dypere)',
    muscle_groups: ['Adductorer'],
    meridian_tension: ['Lever'], meridian_compress: ['Milt/mage'],
    intensity_label: 'Maks', intensity_level: 6,
    duration_min_sec: 120, duration_max_sec: 300,
    notes: 'Krevende, bruk puter under knær',
    is_active: true, sort_order: 10,
    instruksjon: [
      'Kom ned på alle fire. Skyv knærne bredt ut til sidene langs med matten.',
      'Sett under- og overben i 90 graders vinkel. Fotsålene peker opp eller ut.',
      'Senk hoften mot gulvet og støtt deg på underarmene. Slipp alt hold i lysken.',
      'Bruk puter under knærne om det er ubehagelig.',
    ],
    tilpasning: 'Halvfrosk: hold bena samlet og løft hoften til nivå med knærne for mildere versjon. Forfrosk: lie med magen på gulvet, armer strukket frem.',
    kontraindikasjon: 'En av de krevende posene. Stans om du kjenner sterk smerte i lysken. Ikke anbefalt for nybegynnere uten oppvarming.',
  },
  {
    id: 'halv_frosk', slug: 'halv_frosk', name_no: 'Halv frosk', name_en: 'Half Frog',
    category: 'SEAT', archetype: 'Dragonfly',
    function_desc: 'Stretch – adductor ensidig + quad',
    muscle_groups: ['Adductorer', 'Quadriceps'],
    meridian_tension: ['Lever', 'Milt'], meridian_compress: ['Milt/mage'],
    intensity_label: 'Medium-Høy', intensity_level: 4,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: 'Ettben-variant, quad-tøy mulig',
    is_active: true, sort_order: 11,
    instruksjon: [
      'Ligg på siden med det nedre benet strakt.',
      'Bøy det øvre benet fremover og la det hvile mot gulvet.',
      'Strekker adductorer ensidig – mildere variant av frosk. Bytt side.',
    ],
    tilpasning: 'Støtt det øvre kneet med en pute om hoften er stiv.',
    kontraindikasjon: null,
  },
  {
    id: 'hest', slug: 'hest', name_no: 'Hest', name_en: 'Horse',
    category: 'SEAT', archetype: 'Dragonfly',
    function_desc: 'Stretch – adductorer, squat-mobilitet',
    muscle_groups: ['Adductorer'],
    meridian_tension: ['Lever'], meridian_compress: ['Milt/mage'],
    intensity_label: 'Høy', intensity_level: 5,
    duration_min_sec: 120, duration_max_sec: 180,
    notes: 'Stå, bruk blokker under hæler om nødvendig',
    is_active: true, sort_order: 12,
    instruksjon: [
      'Stå med bena bredt fra hverandre – litt bredere enn skulderbredde. Tær peker ut til sidene.',
      'Senk hoften ned i en dyp bred knebøy. Hendene i bønn foran brystet, albuene mot innsiden av knærne.',
      'Bruk blokker under hælene om de ikke når gulvet.',
    ],
    tilpasning: 'Tilsvarende Malasana – squatposisjon. Hold i bolster eller stol foran deg for støtte i starten.',
    kontraindikasjon: 'Ubehag i knær: spre føttene bredere eller hev hælene. Unngå om du har akutte kneskader.',
  },
  {
    id: 'seiza', slug: 'seiza', name_no: 'Seiza', name_en: 'Seiza',
    category: 'SEAT', archetype: 'Saddle',
    function_desc: 'Ankelmobilitet, mild quad-tøy',
    muscle_groups: ['Hoftebøyere', 'Ankler'],
    meridian_tension: ['Milt/mage'], meridian_compress: ['Blære'],
    intensity_label: 'Lav-Medium', intensity_level: 2,
    duration_min_sec: 120, duration_max_sec: 180,
    notes: 'Tradisjonell japansk sitteposisjon',
    is_active: true, sort_order: 13,
    instruksjon: [
      'Kneel med bena samlet. Senk setet ned mot hælene – sett deg tilbake på dem.',
      'La hendene hvile avslappet i fanget. Hold ryggen lett oppreist.',
      'Bruk en pute, teppe eller seiza-benk under setet for å avlaste knærne og anklene.',
    ],
    tilpasning: 'Tradisjonell japansk sittestilling. Svært fleksible kan sitte mellom føttene i stedet for på dem.',
    kontraindikasjon: 'Ubehag bak i knærne – legg en rullet teppe i knekket. Stans om det er skarp smerte i knærne.',
  },

  // SPINE
  {
    id: 'larve', slug: 'larve', name_no: 'Larve', name_en: 'Caterpillar',
    category: 'SPINE', archetype: 'Caterpillar',
    function_desc: 'Stretch – hamstrings, thoracolumbar fascia',
    muscle_groups: ['Hamstrings', 'Thoracolumbar'],
    meridian_tension: ['Nyre/blære'], meridian_compress: ['Milt/mage'],
    intensity_label: 'Medium', intensity_level: 3,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: 'Full forover-bøy sittende, slapp ryggrad',
    is_active: true, sort_order: 14,
    instruksjon: [
      'Sitt med begge bena strakt frem, hip-bredde fra hverandre.',
      'La haken falle mot brystet. Bøy rolig fremover og grip om ankler, legg eller føtter.',
      'La ryggen runde helt naturlig – fra korsryggen og opp til nakken. Slipp alle muskler.',
      'Kjenn strekket flytte seg oppover ryggsøylen ettersom du synker dypere.',
    ],
    tilpasning: 'Bøy knærne litt i starten om hamstrings er stive. Bruk en remme rundt føttene. Sett deg på en pute for å vinkle hoften fremover.',
    kontraindikasjon: 'Unngå om du har korsryggplager der fleksjon er kontraindisert.',
  },
  {
    id: 'sfinks', slug: 'sfinks', name_no: 'Sfinks', name_en: 'Sphinx',
    category: 'SPINE', archetype: 'Saddle',
    function_desc: 'Ryggekstensjon (mild), mage-åpning',
    muscle_groups: ['Thoracolumbar'],
    meridian_tension: ['Milt/mage', 'Nyre'], meridian_compress: ['Nyre/blære'],
    intensity_label: 'Lav', intensity_level: 1,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: 'God innledning til rygg-bøy, albuer under skuldrene',
    is_active: true, sort_order: 15,
    instruksjon: [
      'Ligg på magen. Plasser albuene rett under skuldrene, underarmene parallelle.',
      'Løft brystet rolig og la korsryggen bue. Slipp skuldrene ned fra ørene.',
      'Finn kanten der du kjenner et behagelig trykk i korsryggen – ikke skyv lenger.',
      'Pust dypt ned i magen og la korsryggen synke ved hvert utpust.',
    ],
    tilpasning: 'Skyv albuene lenger frem for å redusere trykket. Legg en pute under albuene for støtte. God innledning til sel.',
    kontraindikasjon: 'Skarp smerte i korsryggen – kom deg ut og hvil på magen. Unngå ved hodepine.',
  },
  {
    id: 'sel', slug: 'sel', name_no: 'Sel', name_en: 'Seal',
    category: 'SPINE', archetype: 'Saddle',
    function_desc: 'Ryggekstensjon (dyp)',
    muscle_groups: ['Thoracolumbar'],
    meridian_tension: ['Milt/mage', 'Nyre'], meridian_compress: ['Nyre/blære'],
    intensity_label: 'Høy', intensity_level: 5,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: 'Armer strekkes, mye kompresjon lumbar',
    is_active: true, sort_order: 16,
    instruksjon: [
      'Fra sfinks, flytt hendene fremover og strekk armene rett ut. La hendene rotere litt utover.',
      'Press brystet opp og la korsryggen bue dypere. Tyngdekraften gjør arbeidet.',
      'Om det kjennes godt: la hodet falle bakover og åpne halsen.',
      'Kom ut: senk brystet rolig til gulvet, snu hodet til siden og hvil kinnet mot hendene.',
    ],
    tilpasning: 'Begynn med korte holds på ett minutt, hvil, gjenta. Spre bena for mer trykk i korsryggen – saml dem for jevnere fordeling.',
    kontraindikasjon: 'Sterk smerte i korsryggen – kom ut øyeblikkelig. Unngå ved svangerskap og hodepine.',
  },
  {
    id: 'kamel', slug: 'kamel', name_no: 'Kamel', name_en: 'Camel',
    category: 'SPINE', archetype: 'Saddle',
    function_desc: 'Ryggekstensjon + hoftebøyer stretch',
    muscle_groups: ['Hoftebøyere', 'Thoracolumbar'],
    meridian_tension: ['Milt/mage'], meridian_compress: ['Blære/nyre'],
    intensity_label: 'Høy', intensity_level: 5,
    duration_min_sec: 60, duration_max_sec: 180,
    notes: 'Mer yang enn yin, korte holds',
    is_active: true, sort_order: 17,
    instruksjon: [
      'Kneel med hoftebredde mellom knærne, tærne peker rett bakover.',
      'Plasser hendene på korsryggen med fingrene pekende ned. Løft brystet opp og bakover.',
      'For mer dybde: nå bak og ta tak i hælene ett om gangen.',
      'Hold brystet åpent og unngå å kollapse i korsryggen – tenk løft fremover og opp.',
    ],
    tilpasning: 'Mer yang enn yin – kortere holds. Tukk tærne under og stå på ballene av føttene om hælene er for langt unna.',
    kontraindikasjon: 'Unngå ved korsrygg- eller nakkeskader. Slutt om du blir svimmel.',
  },
  {
    id: 'snegl', slug: 'snegl', name_no: 'Snegl', name_en: 'Snail',
    category: 'SPINE', archetype: 'Caterpillar',
    function_desc: 'Fleksjon hele ryggraden, hamstrings',
    muscle_groups: ['Thoracolumbar', 'Hamstrings'],
    meridian_tension: ['Blære'], meridian_compress: ['Milt/mage'],
    intensity_label: 'Høy', intensity_level: 5,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: 'Inversjon-kvalitet, unngå ved nakkeskader',
    is_active: true, sort_order: 18,
    instruksjon: [
      'Ligg på ryggen. Støtt hoften med hendene og rull bena langsomt over hodet.',
      'La ryggen runde fullstendig – dette er ikke plogen (halasana). La knærne bøye om nødvendig.',
      'Tyngden hviler på skuldrene, ikke på nakken. Juster hendene for balanse.',
      'For å komme ut: hold hoften med hendene og rull sakte ned. Hvil flatt noen pust etterpå.',
    ],
    tilpasning: 'Erstatt med larve om du ikke ønsker inversjon. La knærne synke mot gulvet for den dypeste ryggrunding.',
    kontraindikasjon: 'Unngå ved nakkeskader, høyt blodtrykk, glaukom, svangerskap og menstruasjon. Forbered nakken med fremoverbøy.',
  },
  {
    id: 'vridde_roter', slug: 'vridde_roter', name_no: 'Vridde røtter', name_en: 'Twisted Roots',
    category: 'SPINE', archetype: 'Twists',
    function_desc: 'Rotasjon thorax + lumbar',
    muscle_groups: ['Obliques', 'Thoracolumbar'],
    meridian_tension: ['Galleblære'], meridian_compress: ['Lever'],
    intensity_label: 'Lav-Medium', intensity_level: 2,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: 'Liggende vrid, god rebound-pose',
    is_active: true, sort_order: 19,
    instruksjon: [
      'Ligg på ryggen med bøyde knær. Åpne armene ut til sidene som vinger.',
      'Kryss bena som i ørneposisjon og la dem falle til én side mot gulvet.',
      'Snu hodet rolig til den andre siden for et fullstendig vrid gjennom hele kroppen.',
      'La tyngdekraften gjøre arbeidet – ikke press. Bytt side.',
    ],
    tilpasning: 'Retning og høyde på knærne endrer hvor i ryggen du kjenner vriden. Høyere knær: øvre rygg. Lavere knær: lumbar.',
    kontraindikasjon: 'Prikking i armene – trekk armen ned mot kroppen. Skulderproblemer – støtt armen med en pute.',
  },
  {
    id: 'kattesvans', slug: 'kattesvans', name_no: 'Kattesvans', name_en: "Cat's Tail",
    category: 'SPINE', archetype: 'Twists',
    function_desc: 'Lateral fleksjon + rotasjon',
    muscle_groups: ['Obliques', 'QL'],
    meridian_tension: ['Galleblære'], meridian_compress: ['Lever'],
    intensity_label: 'Medium', intensity_level: 3,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: 'Liggende sidevri',
    is_active: true, sort_order: 20,
    instruksjon: [
      'Ligg på siden, støtt deg på den nedre albuen. Det nedre benet er strakt.',
      'Bøy det nedre benet og nå bak med den øvre hånden for å ta tak i foten.',
      'Trekk foten forsiktig bort fra deg og la ryggen bue lett bakover.',
      'Legg det øvre benet fremover på gulvet. Kjenn strekket i låret og korsryggen.',
    ],
    tilpasning: 'Legg deg flat ned for en dypere variant som kombinerer vri og ryggebøy. Kan holdes kort (1 min) som motpose til forover-bøyer.',
    kontraindikasjon: 'Unngå om du har akutte korsryggproblemer.',
  },
  {
    id: 'bananastilling', slug: 'bananastilling', name_no: 'Bananastilling', name_en: 'Bananasana',
    category: 'SPINE', archetype: 'Twists',
    function_desc: 'Lateral fleksjon hele kroppen',
    muscle_groups: ['QL', 'Obliques', 'IT-band'],
    meridian_tension: ['Galleblære'], meridian_compress: ['Lever'],
    intensity_label: 'Medium', intensity_level: 3,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: 'Liggende banan-form, mild men effektiv',
    is_active: true, sort_order: 21,
    instruksjon: [
      'Ligg flatt på ryggen med bena samlet og strakt.',
      'Hold setet plant på gulvet – flytt både føtter og overkropp til samme side. Lag en bananform.',
      'Rekk armene over hodet og kryss anklene for ekstra strekk i siden.',
      'Pust rolig, la siden åpne seg for hvert utpust. Bytt side.',
    ],
    tilpasning: 'Kryss den ytre ankelen over den indre for mer strekk. Støtt armene med en bolster om du kjenner prikking i hendene.',
    kontraindikasjon: 'Unngå dype lateralbøy ved korsryggplager.',
  },
  {
    id: 'ponton', slug: 'ponton', name_no: 'Ponton', name_en: 'Pontoon',
    category: 'SPINE', archetype: 'Saddle',
    function_desc: 'Mild ryggekstensjon + hoftebøyer',
    muscle_groups: ['Hoftebøyere'],
    meridian_tension: ['Milt/mage'], meridian_compress: ['Nyre/blære'],
    intensity_label: 'Lav-Medium', intensity_level: 2,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: null,
    is_active: true, sort_order: 22,
    instruksjon: [
      'Ligg på siden med bena lett bøyde, kroppen avslappet og lang.',
      'Slipp alt muskulært hold. La gulvet bære deg fullstendig.',
      'En mild hvilende overgangsposisjon mellom aktive poser.',
    ],
    tilpasning: 'Legg en pute under hodet for komfort.',
    kontraindikasjon: null,
  },
  {
    id: 'knebøy', slug: 'knebøy', name_no: 'Knebøy', name_en: 'Squat',
    category: 'SPINE', archetype: 'Caterpillar',
    function_desc: 'Hoftemobilitet, ankelmobilitet',
    muscle_groups: ['Adductorer', 'Hoftebøyere'],
    meridian_tension: ['Nyre'], meridian_compress: ['Blære'],
    intensity_label: 'Medium', intensity_level: 3,
    duration_min_sec: 120, duration_max_sec: 180,
    notes: 'Malasana, dypt hofteåpnende',
    is_active: true, sort_order: 23,
    instruksjon: [
      'Stå med bena litt bredere enn hip-bredde. Tærne peker litt utover.',
      'Senk deg ned i dyp knebøy. Hendene i bønn foran brystet, albuene presser lett mot knærne innenfra.',
      'Tyngden fordeles jevnt mellom tær og hæler. La korsryggen synke og hoften åpne seg.',
    ],
    tilpasning: 'Legg en brettet teppe under hælene om de ikke når gulvet. Snu og gå fra Dangling til Squat og tilbake flere ganger for å varme opp.',
    kontraindikasjon: 'Ubehag i knærne – spre bena bredere. Unngå ved akutte kneskader.',
  },
  {
    id: 'elefant', slug: 'elefant', name_no: 'Elefant', name_en: 'Elephant',
    category: 'SPINE', archetype: 'Caterpillar',
    function_desc: 'Skuldertøy + hamstrings',
    muscle_groups: ['Hamstrings', 'Scapular'],
    meridian_tension: ['Blære'], meridian_compress: ['Milt'],
    intensity_label: 'Medium', intensity_level: 3,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: null,
    is_active: true, sort_order: 24,
    instruksjon: [
      'Stå med bena hip-bredde fra hverandre, knærne lett bøyde.',
      'Bøy fremover og kryss armene – grip om motsatt albue. La overkroppen henge tung.',
      'Slipp nakken og hodet fullstendig. Svai gjerne fra side til side.',
    ],
    tilpasning: 'Bøy knærne mer for å slippe ryggen og styrke låret. Strekk bena for mer hamstrings-strekk.',
    kontraindikasjon: 'Unngå ved høyt blodtrykk, glaukom eller svimmelhet. Kom opp sakte.',
  },

  // WINGS
  {
    id: 'apne_vinger', slug: 'apne_vinger', name_no: 'Åpne vinger', name_en: 'Open Wings',
    category: 'WINGS', archetype: 'Wings',
    function_desc: 'Skulder + brystkasse-åpning',
    muscle_groups: ['Scapular'],
    meridian_tension: ['Hjerte', 'Lunge'], meridian_compress: ['Tykktarm', 'Tynntarm'],
    intensity_label: 'Medium', intensity_level: 3,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: 'Liggende, armer ut til siden',
    is_active: true, sort_order: 25,
    instruksjon: [
      'Ligg på ryggen. Strekk armene ut til sidene i en T-form.',
      'La brystkassen åpne seg og skuldrene synke tunge mot gulvet.',
      'Pust dypt ned i brystet. Slipp forsiden av kroppen med hvert utpust.',
    ],
    tilpasning: 'Juster armvinkelen – høyere over hodet for skulder, lavere for bryst.',
    kontraindikasjon: null,
  },
  {
    id: 'kryssede_vinger', slug: 'kryssede_vinger', name_no: 'Kryssede vinger', name_en: 'Crossed Wings',
    category: 'WINGS', archetype: 'Wings',
    function_desc: 'Skulder + øvre rygg',
    muscle_groups: ['Scapular'],
    meridian_tension: ['Hjerte', 'Lunge'], meridian_compress: ['Tykktarm'],
    intensity_label: 'Medium', intensity_level: 3,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: null,
    is_active: true, sort_order: 26,
    instruksjon: [
      'Ligg på ryggen. Strekk én arm rett ut til siden. Kryss den andre armen over brystet.',
      'Rull forsiktig over på den utstrakte armsiden og la skulderen synke mot gulvet.',
      'La tyngden åpne skulderleddet gradvis. Bytt side.',
    ],
    tilpasning: 'Bruk en lett pute under hodet for komfort.',
    kontraindikasjon: 'Prikking i armen – juster posisjonen. Unngå ved rotator cuff-skader.',
  },
  {
    id: 'smeltende_hjerte', slug: 'smeltende_hjerte', name_no: 'Smeltende hjerte', name_en: 'Melting Heart',
    category: 'WINGS', archetype: 'Wings',
    function_desc: 'Skulder + thorax-ekst., heart opening',
    muscle_groups: ['Scapular', 'Thoracolumbar'],
    meridian_tension: ['Hjerte', 'Lunge'], meridian_compress: ['Milt/mage'],
    intensity_label: 'Medium-Høy', intensity_level: 4,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: 'Knelen, bryst mot gulvet, hofter over knær',
    is_active: true, sort_order: 27,
    instruksjon: [
      'Fra knestående på alle fire, gå hendene fremover langs matten.',
      'La brystet synke mot gulvet. Hoften holdes rett over knærne – ikke la setet synke bakover.',
      'Pannen eller haken hviler på gulvet eller en bolster. Skuldrene smelter ned.',
      'Pust rolig og la brystet tunge seg lenger ned for hvert utpust.',
    ],
    tilpasning: 'Legg en pute under brystet for støtte. Prøv med én arm strukket frem om skuldrene er stive. Legg teppe under knærne.',
    kontraindikasjon: 'Prikking i hender eller fingre – juster armposisjon. Unngå ved nakkeskader.',
  },
  {
    id: 'hjerteopning', slug: 'hjerteopning', name_no: 'Hjerteåpning', name_en: 'Heart Opening',
    category: 'WINGS', archetype: 'Wings',
    function_desc: 'Thorax-ekst., mellomgulv-tøy',
    muscle_groups: ['Thoracolumbar', 'Scapular'],
    meridian_tension: ['Hjerte'], meridian_compress: ['Nyre'],
    intensity_label: 'Medium', intensity_level: 3,
    duration_min_sec: 180, duration_max_sec: 300,
    notes: 'Liggende, god mot hodepine og tett bryst',
    is_active: true, sort_order: 28,
    instruksjon: [
      'Ligg på ryggen med en rullet teppe eller bolster plassert under skuldrene, på tvers av matten.',
      'La brystet falle åpent mot taket. Hodet hviler på gulvet – slipp nakken.',
      'Armene hviler avslappet ved sidene med håndflatene opp.',
      'Pust dypt ned i brystet og la brystkassen utvide seg.',
    ],
    tilpasning: 'Juster tykkelsen på teppet etter behov. Legg en pute under hodet om nakken føles spent.',
    kontraindikasjon: 'Unngå ved akutte ryggrad- eller nakkeskader.',
  },
  {
    id: 'rullende_panda', slug: 'rullende_panda', name_no: 'Rullende panda', name_en: 'Rolling Panda',
    category: 'WINGS', archetype: 'Wings',
    function_desc: 'Skulder-mobilitet, sidestrekk',
    muscle_groups: ['Scapular'],
    meridian_tension: ['Hjerte', 'Lunge'], meridian_compress: ['Tykktarm'],
    intensity_label: 'Lav', intensity_level: 1,
    duration_min_sec: 120, duration_max_sec: 180,
    notes: null,
    is_active: true, sort_order: 29,
    instruksjon: [
      'Ligg på ryggen. Strekk én arm rett ut til siden i 90 grader fra kroppen.',
      'Rull sakte over på den siden og la tyngden åpne skulderleddet gradvis.',
      'La kroppen bli tung – skulderen smelter mot gulvet. Bytt side.',
    ],
    tilpasning: 'Prøv forskjellige armvinkler – litt over eller under 90 grader – for å treffe ulike deler av skulderen.',
    kontraindikasjon: 'Prikking i armen – juster posisjonen umiddelbart.',
  },

  // REBOUND
  {
    id: 'konstruktiv_hvile', slug: 'konstruktiv_hvile', name_no: 'Konstruktiv hvile', name_en: 'Constructive Rest',
    category: 'REBOUND', archetype: 'Rebound',
    function_desc: 'Nervesystem-reset, rygg-hvile',
    muscle_groups: ['Rygg'],
    meridian_tension: [], meridian_compress: [],
    intensity_label: 'Lav', intensity_level: 1,
    duration_min_sec: 120, duration_max_sec: 300,
    notes: 'Grunnleggende rebound, parasympatisk aktivering',
    is_active: true, sort_order: 30,
    instruksjon: [
      'Ligg på ryggen med bøyde knær og føtter flat på gulvet, hip-bredde fra hverandre.',
      'Armene hviler avslappet ved siden av kroppen med håndflatene opp eller ned.',
      'Korsryggen finner sin naturlige kurve. Lukk øynene og pust rolig.',
      'Aktiver ingenting – la nervesystemet finne ro.',
    ],
    tilpasning: 'En av de mest terapeutiske stillingene for korsryggen. Kan holdes lenge. God mellom intense poser.',
    kontraindikasjon: null,
  },
  {
    id: 'barneposen', slug: 'barneposen', name_no: 'Barneposen', name_en: "Child's Pose",
    category: 'REBOUND', archetype: 'Rebound',
    function_desc: 'Rygg-hvile, fordøyelses-stimulering',
    muscle_groups: ['Thoracolumbar'],
    meridian_tension: ['Blære'], meridian_compress: ['Milt/mage'],
    intensity_label: 'Lav', intensity_level: 1,
    duration_min_sec: 120, duration_max_sec: 300,
    notes: 'Komprimerer magen, rolig avslutning',
    is_active: true, sort_order: 31,
    instruksjon: [
      'Kneel og la setet synke tilbake mot hælene.',
      'Brett overkroppen fremover og hvil pannen på gulvet eller en bolster.',
      'Armene enten strekkes fremover for et aktivt strekk, eller hviler langs kroppen.',
      'Pust rolig ned i magen og la korsryggen synke med hvert utpust.',
    ],
    tilpasning: 'Spre knærne litt for å gi magen plass. Legg en teppe mellom sete og hæler om hoften ikke når ned. Bruk en bolster under brystet.',
    kontraindikasjon: null,
  },
  {
    id: 'liggende_sete', slug: 'liggende_sete', name_no: 'Liggende sete', name_en: 'Reclining Seat',
    category: 'REBOUND', archetype: 'Rebound',
    function_desc: 'Hoftehvile, nøytral stilling',
    muscle_groups: ['Hofter'],
    meridian_tension: [], meridian_compress: [],
    intensity_label: 'Lav', intensity_level: 1,
    duration_min_sec: 120, duration_max_sec: 180,
    notes: null,
    is_active: true, sort_order: 32,
    instruksjon: [
      'Ligg på ryggen med bøyde knær og føtter flat på gulvet.',
      'En nøytral hvilestilling for hoften mellom aktive poser.',
      'Pust rolig. La kroppen integrere det foregående arbeidet.',
    ],
    tilpasning: 'Legg en pute under hodet for komfort.',
    kontraindikasjon: null,
  },
  {
    id: 'stjerne_ser_paa_himmelen', slug: 'stjerne_ser_paa_himmelen', name_no: 'Stjerne ser på himmelen', name_en: 'Star Looking at Sky',
    category: 'REBOUND', archetype: 'Rebound',
    function_desc: 'Ryggliggende hvile + brystexpansjon',
    muscle_groups: ['Rygg'],
    meridian_tension: [], meridian_compress: [],
    intensity_label: 'Lav', intensity_level: 1,
    duration_min_sec: 120, duration_max_sec: 180,
    notes: null,
    is_active: true, sort_order: 33,
    instruksjon: [
      'Ligg flatt på ryggen med bena litt spredt fra hverandre.',
      'Strekk armene litt ut til sidene – håndflatene peker opp.',
      'Slipp all spenning fra kroppen. Integreringsstilling mellom intense seksjoner.',
    ],
    tilpasning: 'La kroppen ligge i den posisjonen som føles mest naturlig.',
    kontraindikasjon: null,
  },
  {
    id: 'savasana', slug: 'savasana', name_no: 'Savasana', name_en: 'Shavasana',
    category: 'REBOUND', archetype: 'Rebound',
    function_desc: 'Full hvile, integrering',
    muscle_groups: ['Hele kroppen'],
    meridian_tension: [], meridian_compress: [],
    intensity_label: 'Lav', intensity_level: 1,
    duration_min_sec: 300, duration_max_sec: 900,
    notes: 'Alltid avslutning av praksis',
    is_active: true, sort_order: 34,
    instruksjon: [
      'Ligg flatt på ryggen, bena litt spredt, armer litt bort fra kroppen med håndflatene opp.',
      'Lukk øynene. Slipp bevisst all spenning fra hvert kroppsdel – fra føtter til ansikt.',
      'La kroppen bli tung som stein. Sinnet er stille og årvåkent – ikke sov.',
      'Bli liggende. Dette er den viktigste posisjonen i praksisen – her integreres alt arbeidet.',
    ],
    tilpasning: 'Bruk et teppe over deg for varme. Legg en pute under knærne for korsryggen. Bruk øyepute for dypere ro.',
    kontraindikasjon: null,
  },
]
